baseURL = 'https://alexdavis.tardis.ac/'
languageCode = 'en-uk'
title = 'alexdavis28'
theme = 'typo'

[taxonomies]
tag = 'portfolio'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Portfolio website for Alex Davis"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hey hey'
homeIntroContent = """
I'm a British Software Engineer / Computer Science student at University of Edinburgh.
I'm liable to take an interest in basically anything, but I've got a particular love for Python and sys-admin work.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/alexander-mark-davis/"

[[params.social]]
name = "github"
url = "https://github.com/alexDavis28/"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"